cmake_minimum_required(VERSION 4.0)
project(DSA_Insult_Generator_Project_2)

set(CMAKE_CXX_STANDARD 14)

add_executable(DSA_Insult_Generator_Project_2
        src/HashTable.hpp
        src/main.cpp
        src/Tree.hpp
        src/Tree.cpp
        src/HashTable.hpp
        src/HashTable.cpp
        src/Word.hpp)
